# Generated by Django 6.0 on 2026-01-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
