# Generated by Django 6.0 on 2026-01-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_latitude_customuser_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='service_type',
            field=models.CharField(blank=True, choices=[('MENAGE', 'Ménage'), ('JARDINAGE', 'Jardinage')], max_length=20, null=True),
        ),
    ]
