# Generated by Django 6.0 on 2026-01-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_prestataireprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestataireImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prestataire_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='prestataireprofile',
            name='images',
            field=models.ManyToManyField(blank=True, to='accounts.prestataireimage'),
        ),
    ]
