# Generated by Django 6.0 on 2026-01-29 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_prestataireimage_prestataireprofile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestataireprofile',
            name='images',
        ),
        migrations.AddField(
            model_name='prestataireimage',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='accounts.prestataireprofile'),
        ),
    ]
