# Generated by Django 6.0 on 2026-01-29 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_prestataireprofile_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataireimage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='accounts.prestataireprofile'),
        ),
    ]
