# Generated by Django 6.0 on 2026-01-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_prestataireimage_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='service_type',
        ),
    ]
